hb_user:
    resource: "@HBUserBundle/Controller/"
    type:     annotation
    prefix:   /

hb_blog:
    resource: "@HBBlogBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"