security:
    encoders:
        HB\BlogBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        
    providers:
        ma_bdd:
            entity:
                class: HB\BlogBundle\Entity\User
                property: login

    firewalls:
        mon_pare_feu:
            pattern: ^/
            anonymous: ~
            form_login: ~
            logout: ~