<?php

namespace HB\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    /**
     * Renvoie les articles pour la page d'accueil
     */

    public function getHomepageArticles($limit = null) {

        return $this->findBy(
                    array('published' => true, 'enabled' => true),
                    array('publishDate' => 'desc'),
                    $limit
                        );
    }
    
    public function getArticlesSearch($str, $limit = 10) {

        
                return $this->createQueryBuilder("a")
                        ->select("a.id", "a.title", "a.content", "a.slug")
                        ->where('a.published = 1')
                        ->andWhere('a.enabled = 1')
                        ->andWhere('a.title LIKE :title')
                        ->orderBy('a.title', 'asc')
                        ->setParameter("title", "%".$str."%")
                        ->setMaxResults($limit)
                        ->getQuery()->getResult();
                        
    }
}
